<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_focus-visible</name>
   <tag></tag>
   <elementGuidId>2fb1b6b1-3695-4c93-b74e-d1b1f14a759a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.focus-visible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus-visible</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;AuthWrapperstyled__AuthContainer-sc-1plclw5-0 icINpf&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 fNJOVH AuthWrapperstyled__StyledCard-sc-1plclw5-1 krbqFL AuthWrapperstyled__StyledCard-sc-1plclw5-1 krbqFL&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 iBCjCr AuthWrapperstyled__StyledCard2-sc-1plclw5-3 leMQwc AuthWrapperstyled__StyledCard2-sc-1plclw5-3 leMQwc&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 boVWpZ&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 lVNIS Auth__StyledCard-sc-f9huj5-1 kYLiKq Auth__StyledCard-sc-f9huj5-1 kYLiKq&quot;]/div[@class=&quot;Input__InputContainer-sc-1goybxj-0 dTvkEe&quot;]/input[@class=&quot;focus-visible&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/div/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
