<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>08f5f1d3-0c8c-4171-a726-95e8356f60d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;tel&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Mobile__LayoutMobile-sc-rocs5d-0 dsHqgO&quot;]/main[@class=&quot;main-mobile&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 gdXuFn AuthWrapperstyled__StyledCard-sc-1plclw5-1 bKnfzS AuthWrapperstyled__StyledCard-sc-1plclw5-1 bKnfzS&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 gdXuFn AuthWrapperstyled__StyledCard2Mobile-sc-1plclw5-2 bdxXdh AuthWrapperstyled__StyledCard2Mobile-sc-1plclw5-2 bdxXdh&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 dEDKtE&quot;]/div[@class=&quot;Card__BaseCard-sc-b3n78k-0 djgmkN Auth__StyledCard-sc-f9huj5-1 kYLiKq Auth__StyledCard-sc-f9huj5-1 kYLiKq&quot;]/div[@class=&quot;Input__InputContainer-sc-1goybxj-0 jtShNG&quot;]/input[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
