<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Making Appointment TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2404419f-c626-4be9-9e04-396ef5abeb99</testSuiteGuid>
   <testCaseLink>
      <guid>bb4468ce-2add-4036-8dff-9c8fa66af64e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Web Application/CURA Healthcare Service/Appointment/Open Browser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6672f50e-cc91-46c5-8268-965e642d0dec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Web Application/CURA Healthcare Service/Appointment/Click on Login Link</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0fe732dc-4d1d-4e62-8133-e27caa2b07dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Web Application/CURA Healthcare Service/Appointment/Login Application</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22c3aef3-816d-4b8b-9361-7e2fe7868a4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36200139-eb2c-4b98-9c40-3a2cf9e07dcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74e718d6-95ad-4c24-8230-afd336f47b26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efb6b31f-a649-4af1-88c5-36fb3ddec05c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Web Application/CURA Healthcare Service/Appointment/Make Appointment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0b6b7782-e2b4-443c-b4ff-011067847fe9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AppTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0b6b7782-e2b4-443c-b4ff-011067847fe9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Facility</value>
         <variableId>3a5237a8-de02-4bcc-97d0-166556d4175d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b6b7782-e2b4-443c-b4ff-011067847fe9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>VisitDate</value>
         <variableId>e6a6dd4c-9add-4c82-a20c-5650ea48e1d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b6b7782-e2b4-443c-b4ff-011067847fe9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Comment</value>
         <variableId>4fafdd75-f2c4-4ca5-b396-eb529b6ae7c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e20b47b-2a89-49cc-8c5a-a12814c8553c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Web Application/CURA Healthcare Service/Appointment/Logout Application</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
