<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WebTable</name>
   <tag></tag>
   <elementGuidId>c11f4a7f-be99-4316-b893-e6e6d6f2c907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='customers']/tbody</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='customers']/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='customers']/tbody</value>
   </webElementProperties>
</WebElementEntity>
