<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_httpscredit-suisse.zoom.usj93572116916_9eb7a1</name>
   <tag></tag>
   <elementGuidId>d11a249e-22a8-4328-9543-bdfc024ba96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-opens-details='true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.JClzi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JClzi</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://credit-suisse.zoom.us/j/93572116916?pwd=a2FGSFNlcFUrOGhKVkFVRk0yMDVIZz09</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c57&quot;)/div[@class=&quot;YvjgZe Qbfsob&quot;]/div[@class=&quot;WJVfWe A3o4Oe&quot;]/div[@class=&quot;NlL62b EfQccc elYzab-cXXICe-Hjleke EiZ8Dd MmaWIb jKgTF&quot;]/div[@class=&quot;lFe10c&quot;]/div[@class=&quot;YSbf0c&quot;]/div[@class=&quot;Jmftzc gVNoLb  EiZ8Dd&quot;]/span[@class=&quot;JClzi&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon TestOps | shakeup'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon demo for GOSI'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://credit-suisse.zoom.us/j/93572116916?pwd=a2FGSFNlcFUrOGhKVkFVRk0yMDVIZz09']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c57']/div[3]/div[2]/div[2]/div[2]/div/div[2]/span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/span[3]</value>
   </webElementXpaths>
</WebElementEntity>
