<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS Review Form Sections</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>45be163b-9d3d-4f99-ac48-3958c8690b70</testSuiteGuid>
   <testCaseLink>
      <guid>3d38f50a-d238-4154-ba42-55135db1c40d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Sabri/Login into Application</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7928147e-d4b7-4132-9fdc-6ac2bcdeff8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24c9f4ac-d7bf-4d5b-a07c-779ee7a49ebc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dad4c92-8254-4166-8ee8-4eaba045ab7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07247a77-548e-4d9d-b900-2e595eeace91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95aceff8-bc32-4803-a44f-a65f8947ad4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Sabri/Review Form Section</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9e340399-0a4a-4c46-99c6-a7b7ad7988bb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF Sabri/ReviewFormSections</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9e340399-0a4a-4c46-99c6-a7b7ad7988bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Question</value>
         <variableId>51515908-c9d3-4892-9f47-3f22c9cda246</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e340399-0a4a-4c46-99c6-a7b7ad7988bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Type</value>
         <variableId>0c0d5458-9e19-4b62-a81c-8b9dac7e89e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e340399-0a4a-4c46-99c6-a7b7ad7988bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Options</value>
         <variableId>37bf351e-e68b-4a03-b3b0-30288668b7a7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
