<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS Rating Scale</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2ebb4ccc-b6f7-49f2-92bb-d0cf53c5618a</testSuiteGuid>
   <testCaseLink>
      <guid>d7f71503-38bc-4db7-a507-7581bd7bb143</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Sabri/Login into Application</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7928147e-d4b7-4132-9fdc-6ac2bcdeff8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24c9f4ac-d7bf-4d5b-a07c-779ee7a49ebc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dad4c92-8254-4166-8ee8-4eaba045ab7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07247a77-548e-4d9d-b900-2e595eeace91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd0a89dd-2507-45a9-b79a-0bf6eb7573b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Sabri/Switch to rating Scale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2e5cdaf-9c43-40ee-8077-0ccdf9b585b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad281c67-c85e-4ada-995d-80bfded8debc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff5fffe8-c534-4d2f-8094-476c5e8716f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fc9930b-a5de-49f9-b426-ccaf3f4a760c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b871581-9117-4a61-94ab-61ee1cdc670c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Sabri/Fill the Rating Table</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cd5d29bb-27e5-4234-9788-bf959b84ab4b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF Sabri/SabriDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cd5d29bb-27e5-4234-9788-bf959b84ab4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>rating</value>
         <variableId>77810688-a7d4-4f51-a168-5360a59aa1e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd5d29bb-27e5-4234-9788-bf959b84ab4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>shortCode</value>
         <variableId>cab1459a-9a38-4e98-8174-12fbc5791b8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd5d29bb-27e5-4234-9788-bf959b84ab4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>d0c1f28a-a46b-49d3-88db-497f912660c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd5d29bb-27e5-4234-9788-bf959b84ab4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>note</value>
         <variableId>38a909a5-a3e8-4b0f-a3dc-6a78a0a61954</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>493c5590-20ad-4e0c-bf03-bc54a3e05bda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Sabri/Save and Close</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3205a89d-2825-447d-8dc9-1bc4ca7e0481</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4850da73-1b2a-4ca0-9d1c-c3c1a3e7e45f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6d63b3-8ce0-4262-a974-e0e038f77ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd40c56e-fb83-46c8-8df7-2168854632f4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
